name: CD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    name: Example deploy
    environment: example-environment
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello World!"

  compare_shas:
    name: Get last deployment
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        env:
          GITHUB_CONTEXT_SHA: ${{ github.sha }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        with:
          script: |
            const { GITHUB_CONTEXT_SHA, GITHUB_HEAD_REF } = process.env;

            const result = await github.rest.repos.listDeployments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              environment: "example-environment",
              per_page: 1,
            });

            const githubScriptSha = context.sha;
            const githubContextSha = GITHUB_CONTEXT_SHA;

            const refSections = GITHUB_HEAD_REF.split("/");
            const branch = refSections[refSections.length - 1];

            const latestDeploy = result.data[0];
            const currentDeployIsLatest = latestDeploy.sha === branch;

            console.warn(`githubScriptSha: ${githubScriptSha}`);
            console.warn(`githubContextSha: ${githubContextSha}`);
            console.warn(`deploymentSha: ${latestDeploy.sha}`);
