name: CD

on: push

jobs:
  deploy:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: |
          echo "Hello World!"

  generate_cat:
    needs: deploy
    uses: Administrate/github-actions/.github/workflows/generate_cat.yml@PLAT-23311-stop-generating-CATs
    name: Generate CAT
    secrets: inherit
